services:
  pnpm:
    build:
      context: ./images/pnpm
      network: host
    cap_add:
      # Minimum permissions for Docker User Mirror entrypoint:
      - CAP_SETGID # Needed to switch from root to another user.
      - CAP_SETUID # Needed to switch from root to another user.
      - CAP_SETPCAP # Needed to change permissions when switching users.
      - CAP_CHOWN # Needed to write changes to /etc/gshadow and /etc/shadow.
      - CAP_DAC_OVERRIDE # Needed for Podman.
    cap_drop: [ALL]
    entrypoint: [/entrypoint, --, pnpm]
    network_mode: host
    volumes:
      # Bind the current directory to the working directory inside the container.
      - type: bind
        source: ./
        target: /rollup-plugin-userscript
    
    working_dir: /rollup-plugin-userscript